<?php

function nk_an_home_install() {
    $menu = array(
        'menu_name' => 'nk_an_top_menu',
        'title' => 'Nokia Android Menu',
        'description' => 'Nokia android top menu',
    );
    $exists = db_query("SELECT title FROM {menu_custom} WHERE menu_name=:menu_name", array(':menu_name' => $menu['menu_name']))->fetchField();
    // Save the record if the data does not exist
    if (!$exists) {
        menu_save($menu);
    }
}

?>
